### ISSUE TITLE
Separate link to the Hub Champion Training

### ISSUE THREAD

**Issue by jnywong** [czi-catalystproject/czi-catalystproject.github.io#6]
Host Hub Champion Training using the `.cloud` rather than the `.github.io` domain

**Comment by jnywong** [comment]
@jmunroe I think this requires admin privileges on NameCheap to update the CNAME record?

I want https://czi-catalystproject.github.io/hub-champion-training/ to point to https://catalystproject.cloud/hub-champion-training/.

Relevant GH docs about [using a custom domain across multiple repositories](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#using-a-custom-domain-across-multiple-repositories)

**Comment by jmunroe** [comment]
I think have the right credentials to make this happen. Working on it.

**Comment by jmunroe** [comment]
GitHub treats the repository `orgization_name.github.io` as a special repository. If a Custom Domain is set for this repository then the 'default' domain for all other project pages (such as the `hub-champion-training` site will appear using that custom domain.

I have just renamed this repo from `website` to `czi-catalystproject.github.io`  (no change in behavior since https://catalystproject.cloud/ already was configured to map to this repository)

But now, the url associated with the `hub-champion-training` repo has be automatically changed to https://catalystproject.cloud/hub-champion-training which I think closes this issue.
